GAME_TITLE = "LOVE"

GAME_W = 272
GAME_H = 208

TILE_W = 16
TILE_H = 16
TILE_SCALE_X = 1 / 3
TILE_SCALE_Y = 1 / 3
CHARACTER_W = 16
CHARACTER_H = 20
DIALOG_W = GAME_W / TILE_W
DIALOG_H = 5
PORTRAIT_W = 3 * TILE_W
PORTRAIT_H = 3 * TILE_H

ACTOR_MOVE_DURATION = 0.25
ACTOR_MOVE_DELAY = 1
