GAME_TITLE = "LOVE"

TILE_W = 48
TILE_H = 48
TILES_X = 17
TILES_Y = 13
GAME_W = TILES_X * TILE_W
GAME_H = TILES_Y * TILE_H

CHARACTER_FRAMES = 3
CHARACTERS_PER_COL = 4
DIALOG_W = GAME_W / TILE_W
DIALOG_H = 5
PORTRAIT_W = 3 * TILE_W
PORTRAIT_H = 3 * TILE_H

ACTOR_MOVE_DURATION = 0.25
ACTOR_MOVE_DELAY = 1

MAX_LEVEL = 99
